# Generated by Django 4.2.1 on 2023-05-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="lists.list"
            ),
        ),
    ]
